// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using assignment3.Models;

namespace assignment3.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20210324002756_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("assignment3.Models.Films", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("films");

                    b.HasData(
                        new
                        {
                            id = -6,
                            category = "Action/Adventure",
                            director = "Joss Whedon",
                            edited = false,
                            lent = "",
                            notes = "Awesome",
                            rating = "PG-13",
                            title = "The Avengers",
                            year = 2012
                        },
                        new
                        {
                            id = -5,
                            category = "Action/Adventure",
                            director = "Christopher Nolan",
                            edited = false,
                            lent = "",
                            notes = "",
                            rating = "PG-13",
                            title = "Batman Begins",
                            year = 2005
                        },
                        new
                        {
                            id = -4,
                            category = "Comedy",
                            director = "Tom Shadyac",
                            edited = false,
                            lent = "",
                            notes = "",
                            rating = "PG-13",
                            title = "Ace Ventura: Pet Detective",
                            year = 1994
                        },
                        new
                        {
                            id = -3,
                            category = "Drama",
                            director = "Frank Darabont",
                            edited = true,
                            lent = "",
                            notes = "",
                            rating = "R",
                            title = "The Shawshank Redemption",
                            year = 1994
                        },
                        new
                        {
                            id = -2,
                            category = "Family",
                            director = "John Lasseter",
                            edited = false,
                            lent = "Spencer",
                            notes = "the kids LOVED it",
                            rating = "G",
                            title = "Cars",
                            year = 2006
                        },
                        new
                        {
                            id = -1,
                            category = "Horror/Suspense",
                            director = "Gore Verbinski",
                            edited = false,
                            lent = "",
                            notes = "never again",
                            rating = "PG-13",
                            title = "The Ring",
                            year = 2002
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
